INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AF', 'Afghanistan', 53.66);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AL', 'Albania', 89.74);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('DZ', 'Algeria', 89.99);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('DS', 'American Samoa', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AD', 'Andorra', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AO', 'Angola', 129.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AI', 'Anguilla', 2.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AQ', 'Antarctica', null);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AG', 'Antigua and Barbuda', 2.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AR', 'Argentina', 13.81);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AM', 'Armenia', 379.49);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AW', 'Aruba', 1.39);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AU', 'Australia', 1.02);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AT', 'Austria', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AZ', 'Azerbaijan', 1.33);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BS', 'Bahamas', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BH', 'Bahrain', 0.29);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BD', 'Bangladesh', 64.79);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BB', 'Barbados', 1.56);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BY', 'Belarus', 1.57);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BE', 'Belgium', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BZ', 'Belize', 1.56);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BJ', 'Benin', 439.52);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BM', 'Bermuda', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BT', 'Bhutan', 50.56);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BO', 'Bolivia', 5.36);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BA', 'Bosnia and Herzegovina', 1.32);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BW', 'Botswana', 8.25);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BV', 'Bouvet Island', 6.39);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BR', 'Brazil', 2.56);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('IO', 'British Indian Ocean Territory', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BN', 'Brunei Darussalam', 1.07);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BG', 'Bulgaria', 1.32);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BF', 'Burkina Faso', 439.52);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('BI', 'Burundi', 1361.30);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('KH', 'Cambodia', 3149.50);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CM', 'Cameroon', 442.58);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CA', 'Canada', 1.00);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CV', 'Cape Verde', 74.48);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('KY', 'Cayman Islands', 0.64);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CF', 'Central African Republic', 442.58);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TD', 'Chad', 442.58);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CL', 'Chile', 496.17);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CN', 'China', 5.19);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CX', 'Christmas Island', 1.02);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CC', 'Cocos (Keeling) Islands', 1.02);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CO', 'Colombia', 2375.80);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('KM', 'Comoros', 330.96);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CG', 'Congo', 442.58);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CK', 'Cook Islands', 1.13);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CR', 'Costa Rica', 441.66);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('HR', 'Croatia (Hrvatska)', 5.09);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CU', 'Cuba', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CY', 'Cyprus', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CZ', 'Czech Republic', 17.25);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('DK', 'Denmark', 5.02);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('DJ', 'Djibouti', 138.39);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('DM', 'Dominica', 2.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('DO', 'Dominican Republic', 36.81);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TP', 'East Timor', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('EC', 'Ecuador', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('EG', 'Egypt', 13.77);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SV', 'El Salvador', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GQ', 'Equatorial Guinea', 442.58);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('ER', 'Eritrea', 11.97);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('EE', 'Estonia', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('ET', 'Ethiopia', 21.17);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('FK', 'Falkland Islands (Malvinas)', 0.60);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('FO', 'Faroe Islands', 5.02);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('FJ', 'Fiji', 1.62);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('FI', 'Finland', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('FR', 'France', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('FX', 'France, Metropolitan', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GF', 'French Guiana', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PF', 'French Polynesia', 80.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TF', 'French Southern Territories', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GA', 'Gabon', 442.58);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GM', 'Gambia', 36.74);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GE', 'Georgia', 2.03);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('DE', 'Germany', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GH', 'Ghana', 3.46);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GI', 'Gibraltar', 0.60);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GK', 'Guernsey', 0.59);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GR', 'Greece', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GL', 'Greenland', 5.02);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GD', 'Grenada', 2.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GP', 'Guadeloupe', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GU', 'Guam', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GT', 'Guatemala', 5.75);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GN', 'Guinea', 7038.80);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GW', 'Guinea-Bissau', 439.52);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GY', 'Guyana', 159.88);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('HT', 'Haiti', 47.95);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('HM', 'Heard and Mc Donald Islands', 1.02);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('HN', 'Honduras', 18.38);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('HK', 'Hong Kong', 6.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('HU', 'Hungary', 210.26);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('IS', 'Iceland', 82.84);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('IN', 'India', 50.91);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('IM', 'Isle of Man', 0.59);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('ID', 'Indonesia', 10573.00);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('IR', 'Iran (Islamic Republic of)', 27469.00);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('IQ', 'Iraq', 912.52);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('IE', 'Ireland', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('IL', 'Israel', 2.75);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('IT', 'Italy', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CI', 'Ivory Coast', 439.52);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('JE', 'Jersey', 0.59);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('JM', 'Jamaica', 98.37);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('JP', 'Japan', 89.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('JO', 'Jordan', 0.55);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('KZ', 'Kazakhstan', 261.05);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('KE', 'Kenya', 80.92);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('KI', 'Kiribati', 1.02);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('KP', 'Korea, Democratic People''s Republic of', 708.97);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('KR', 'Korea, Republic of', 872.21);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('XK', 'Kosovo', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('KW', 'Kuwait', 0.24);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('KG', 'Kyrgyzstan', 54.16);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('LA', 'Lao People''s Democratic Republic', 6498.40);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('LV', 'Latvia', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('LB', 'Lebanon', 1178.80);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('LS', 'Lesotho', 11.14);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('LR', 'Liberia', 93.34);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('LY', 'Libyan Arab Jamahiriya', 1.08);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('LI', 'Liechtenstein', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('LT', 'Lithuania', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('LU', 'Luxembourg', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MO', 'Macau', 6.29);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MK', 'Macedonia', 41.38);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MG', 'Madagascar', 2474.10);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MW', 'Malawi', 560.74);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MY', 'Malaysia', 3.31);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MV', 'Maldives', 12.19);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('ML', 'Mali', 439.52);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MT', 'Malta', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MH', 'Marshall Islands', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MQ', 'Martinique', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MR', 'Mauritania', 274.81);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MU', 'Mauritius', 26.89);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TY', 'Mayotte', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MX', 'Mexico', 15.01);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('FM', 'Micronesia, Federated States of', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MD', 'Moldova, Republic of', 13.64);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MC', 'Monaco', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MN', 'Mongolia', 1915.10);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('ME', 'Montenegro', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MS', 'Montserrat', 2.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MA', 'Morocco', 7.46);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MZ', 'Mozambique', 47.21);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MM', 'Myanmar', 1067.20);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NA', 'Namibia', 11.13);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NR', 'Nauru', 1.02);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NP', 'Nepal', 81.07);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NL', 'Netherlands', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AN', 'Netherlands Antilles', 1.39);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NC', 'New Caledonia', 80.16);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NZ', 'New Zealand', 1.13);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NI', 'Nicaragua', 23.81);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NE', 'Niger', 439.52);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NG', 'Nigeria', 276.32);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NU', 'Niue', 1.13);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NF', 'Norfolk Island', 1.02);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('MP', 'Northern Mariana Islands', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('NO', 'Norway', 6.39);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('OM', 'Oman', 0.30);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PK', 'Pakistan', 82.23);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PW', 'Palau', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PS', 'Palestine', 2.75);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PA', 'Panama', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PG', 'Papua New Guinea', 2.54);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PY', 'Paraguay', 4409.40);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PE', 'Peru', 2.54);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PH', 'Philippines', 40.25);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PN', 'Pitcairn', 1.13);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PL', 'Poland', 2.87);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PT', 'Portugal', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PR', 'Puerto Rico', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('QA', 'Qatar', 2.99);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('RE', 'Reunion', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('RO', 'Romania', 3.12);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('RU', 'Russian Federation', 46.44);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('RW', 'Rwanda', 650.70);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('KN', 'Saint Kitts and Nevis', 2.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('LC', 'Saint Lucia', 2.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('VC', 'Saint Vincent and the Grenadines', 2.11);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('WS', 'Samoa', 2.01);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SM', 'San Marino', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('ST', 'Sao Tome and Principe', 16550.00);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SA', 'Saudi Arabia', 2.94);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SN', 'Senegal', 439.52);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('RS', 'Serbia', 79.73);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SC', 'Seychelles', 10.35);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SL', 'Sierra Leone', 5964.80);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SG', 'Singapore', 1.07);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SK', 'Slovakia', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SI', 'Slovenia', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SB', 'Solomon Islands', 6.09);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SO', 'Somalia', 436.01);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('ZA', 'South Africa', 11.14);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GS', 'South Georgia South Sandwich Islands', 0.59);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('ES', 'Spain', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('LK', 'Sri Lanka', 120.04);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SH', 'St. Helena', 0.60);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('PM', 'St. Pierre and Miquelon', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SD', 'Sudan', 5.26);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SR', 'Suriname', 5.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SJ', 'Svalbard and Jan Mayen Islands', 6.39);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SZ', 'Swaziland', 11.13);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SE', 'Sweden', 6.57);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('CH', 'Switzerland', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('SY', 'Syrian Arab Republic', 403.12);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TW', 'Taiwan', 23.64);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TJ', 'Tajikistan', 6.89);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TZ', 'Tanzania, United Republic of', 1750.30);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TH', 'Thailand', 25.93);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TG', 'Togo', 439.52);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TK', 'Tokelau', 1.13);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TO', 'Tonga', 1.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TT', 'Trinidad and Tobago', 5.25);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TN', 'Tunisia', 1.96);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TR', 'Turkey', 3.04);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TM', 'Turkmenistan', 2.76);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TC', 'Turks and Caicos Islands', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('TV', 'Tuvalu', 1.02);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('UG', 'Uganda', 2836.80);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('UA', 'Ukraine', 20.90);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('AE', 'United Arab Emirates', 2.87);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('GB', 'United Kingdom', 0.59);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('US', 'United States', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('UM', 'United States minor outlying islands', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('UY', 'Uruguay', 22.83);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('UZ', 'Uzbekistan', 6301.40);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('VU', 'Vanuatu', 82.83);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('VA', 'Vatican City State', 0.68);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('VE', 'Venezuela', 8.74);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('VN', 'Vietnam', 17769.00);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('VG', 'Virgin Islands (British)', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('VI', 'Virgin Islands (U.S.)', 0.78);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('WF', 'Wallis and Futuna Islands', 80.14);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('EH', 'Western Sahara', 7.46);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('YE', 'Yemen', 195.64);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('ZR', 'Zaire', 1225.40);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('ZM', 'Zambia', 7839.51);
INSERT INTO countries(country_code, country_name, exchange_rate) VALUES ('ZW', 'Zimbabwe', 0.78);