INSERT INTO countries(country_code, country_name) VALUES ('AF', 'Afghanistan', 53.66);
INSERT INTO countries(country_code, country_name) VALUES ('AL', 'Albania', 89.74);
INSERT INTO countries(country_code, country_name) VALUES ('DZ', 'Algeria', 89.99);
INSERT INTO countries(country_code, country_name) VALUES ('DS', 'American Samoa', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('AD', 'Andorra', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('AO', 'Angola', 129.11);
INSERT INTO countries(country_code, country_name) VALUES ('AI', 'Anguilla', 2.11);
INSERT INTO countries(country_code, country_name) VALUES ('AQ', 'Antarctica', null);
INSERT INTO countries(country_code, country_name) VALUES ('AG', 'Antigua and Barbuda', 2.11);
INSERT INTO countries(country_code, country_name) VALUES ('AR', 'Argentina', 13.81);
INSERT INTO countries(country_code, country_name) VALUES ('AM', 'Armenia', 379.49);
INSERT INTO countries(country_code, country_name) VALUES ('AW', 'Aruba', 1.39);
INSERT INTO countries(country_code, country_name) VALUES ('AU', 'Australia', 1.02);
INSERT INTO countries(country_code, country_name) VALUES ('AT', 'Austria', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('AZ', 'Azerbaijan', 1.33);
INSERT INTO countries(country_code, country_name) VALUES ('BS', 'Bahamas', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('BH', 'Bahrain', 0.29);
INSERT INTO countries(country_code, country_name) VALUES ('BD', 'Bangladesh', 64.79);
INSERT INTO countries(country_code, country_name) VALUES ('BB', 'Barbados', 1.56);
INSERT INTO countries(country_code, country_name) VALUES ('BY', 'Belarus', null);
INSERT INTO countries(country_code, country_name) VALUES ('BE', 'Belgium', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('BZ', 'Belize', 1.56);
INSERT INTO countries(country_code, country_name) VALUES ('BJ', 'Benin', 439.52);
INSERT INTO countries(country_code, country_name) VALUES ('BM', 'Bermuda', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('BT', 'Bhutan', 50.56);
INSERT INTO countries(country_code, country_name) VALUES ('BO', 'Bolivia', 5.36);
INSERT INTO countries(country_code, country_name) VALUES ('BA', 'Bosnia and Herzegovina', 1.32);
INSERT INTO countries(country_code, country_name) VALUES ('BW', 'Botswana', 8.25);
INSERT INTO countries(country_code, country_name) VALUES ('BV', 'Bouvet Island', null);
INSERT INTO countries(country_code, country_name) VALUES ('BR', 'Brazil', 2.56);
INSERT INTO countries(country_code, country_name) VALUES ('IO', 'British Indian Ocean Territory', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('BN', 'Brunei Darussalam', 1.07);
INSERT INTO countries(country_code, country_name) VALUES ('BG', 'Bulgaria', 1.32);
INSERT INTO countries(country_code, country_name) VALUES ('BF', 'Burkina Faso', 439.52);
INSERT INTO countries(country_code, country_name) VALUES ('BI', 'Burundi', 1361.30);
INSERT INTO countries(country_code, country_name) VALUES ('KH', 'Cambodia', 3149.50);
INSERT INTO countries(country_code, country_name) VALUES ('CM', 'Cameroon', 442.58);
INSERT INTO countries(country_code, country_name) VALUES ('CA', 'Canada', 1.00);
INSERT INTO countries(country_code, country_name) VALUES ('CV', 'Cape Verde', 74.48);
INSERT INTO countries(country_code, country_name) VALUES ('KY', 'Cayman Islands', 0.64);
INSERT INTO countries(country_code, country_name) VALUES ('CF', 'Central African Republic', 442.58);
INSERT INTO countries(country_code, country_name) VALUES ('TD', 'Chad', 442.58);
INSERT INTO countries(country_code, country_name) VALUES ('CL', 'Chile', 496.17);
INSERT INTO countries(country_code, country_name) VALUES ('CN', 'China', 5.19);
INSERT INTO countries(country_code, country_name) VALUES ('CX', 'Christmas Island', 1.02);
INSERT INTO countries(country_code, country_name) VALUES ('CC', 'Cocos (Keeling) Islands', 1.02);
INSERT INTO countries(country_code, country_name) VALUES ('CO', 'Colombia', 2375.80);
INSERT INTO countries(country_code, country_name) VALUES ('KM', 'Comoros', 330.96);
INSERT INTO countries(country_code, country_name) VALUES ('CG', 'Congo', 442.58);
INSERT INTO countries(country_code, country_name) VALUES ('CK', 'Cook Islands', null);
INSERT INTO countries(country_code, country_name) VALUES ('CR', 'Costa Rica', 441.66);
INSERT INTO countries(country_code, country_name) VALUES ('HR', 'Croatia (Hrvatska)', 5.09);
INSERT INTO countries(country_code, country_name) VALUES ('CU', 'Cuba', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('CY', 'Cyprus', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('CZ', 'Czech Republic', 17.25);
INSERT INTO countries(country_code, country_name) VALUES ('DK', 'Denmark', 5.02);
INSERT INTO countries(country_code, country_name) VALUES ('DJ', 'Djibouti', 138.39);
INSERT INTO countries(country_code, country_name) VALUES ('DM', 'Dominica', 2.11);
INSERT INTO countries(country_code, country_name) VALUES ('DO', 'Dominican Republic', 36.81);
INSERT INTO countries(country_code, country_name) VALUES ('TP', 'East Timor', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('EC', 'Ecuador', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('EG', 'Egypt', 13.77);
INSERT INTO countries(country_code, country_name) VALUES ('SV', 'El Salvador', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('GQ', 'Equatorial Guinea', 442.58);
INSERT INTO countries(country_code, country_name) VALUES ('ER', 'Eritrea', 11.97);
INSERT INTO countries(country_code, country_name) VALUES ('EE', 'Estonia', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('ET', 'Ethiopia', 21.17);
INSERT INTO countries(country_code, country_name) VALUES ('FK', 'Falkland Islands (Malvinas)', null);
INSERT INTO countries(country_code, country_name) VALUES ('FO', 'Faroe Islands', null);
INSERT INTO countries(country_code, country_name) VALUES ('FJ', 'Fiji', 1.62);
INSERT INTO countries(country_code, country_name) VALUES ('FI', 'Finland', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('FR', 'France', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('FX', 'France, Metropolitan', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('GF', 'French Guiana', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('PF', 'French Polynesia', 80.11);
INSERT INTO countries(country_code, country_name) VALUES ('TF', 'French Southern Territories', null);
INSERT INTO countries(country_code, country_name) VALUES ('GA', 'Gabon', 442.58);
INSERT INTO countries(country_code, country_name) VALUES ('GM', 'Gambia', 36.74);
INSERT INTO countries(country_code, country_name) VALUES ('GE', 'Georgia', 2.03);
INSERT INTO countries(country_code, country_name) VALUES ('DE', 'Germany', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('GH', 'Ghana', 3.46);
INSERT INTO countries(country_code, country_name) VALUES ('GI', 'Gibraltar', 0.60);
INSERT INTO countries(country_code, country_name) VALUES ('GK', 'Guernsey', null);
INSERT INTO countries(country_code, country_name) VALUES ('GR', 'Greece', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('GL', 'Greenland', 5.02);
INSERT INTO countries(country_code, country_name) VALUES ('GD', 'Grenada', 2.11);
INSERT INTO countries(country_code, country_name) VALUES ('GP', 'Guadeloupe', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('GU', 'Guam', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('GT', 'Guatemala', 5.75);
INSERT INTO countries(country_code, country_name) VALUES ('GN', 'Guinea', 7038.80);
INSERT INTO countries(country_code, country_name) VALUES ('GW', 'Guinea-Bissau', 439.52);
INSERT INTO countries(country_code, country_name) VALUES ('GY', 'Guyana', 159.88);
INSERT INTO countries(country_code, country_name) VALUES ('HT', 'Haiti', 47.95);
INSERT INTO countries(country_code, country_name) VALUES ('HM', 'Heard and Mc Donald Islands', null);
INSERT INTO countries(country_code, country_name) VALUES ('HN', 'Honduras', 18.38);
INSERT INTO countries(country_code, country_name) VALUES ('HK', 'Hong Kong', 6.11);
INSERT INTO countries(country_code, country_name) VALUES ('HU', 'Hungary', 210.26);
INSERT INTO countries(country_code, country_name) VALUES ('IS', 'Iceland', 82.84);
INSERT INTO countries(country_code, country_name) VALUES ('IN', 'India', 50.91);
INSERT INTO countries(country_code, country_name) VALUES ('IM', 'Isle of Man', null);
INSERT INTO countries(country_code, country_name) VALUES ('ID', 'Indonesia', 10573.00);
INSERT INTO countries(country_code, country_name) VALUES ('IR', 'Iran (Islamic Republic of)', 27469.00);
INSERT INTO countries(country_code, country_name) VALUES ('IQ', 'Iraq', 912.52);
INSERT INTO countries(country_code, country_name) VALUES ('IE', 'Ireland', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('IL', 'Israel', 2.75);
INSERT INTO countries(country_code, country_name) VALUES ('IT', 'Italy', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('CI', 'Ivory Coast', 439.52);
INSERT INTO countries(country_code, country_name) VALUES ('JE', 'Jersey', null);
INSERT INTO countries(country_code, country_name) VALUES ('JM', 'Jamaica', 98.37);
INSERT INTO countries(country_code, country_name) VALUES ('JP', 'Japan', 89.11);
INSERT INTO countries(country_code, country_name) VALUES ('JO', 'Jordan', 0.55);
INSERT INTO countries(country_code, country_name) VALUES ('KZ', 'Kazakhstan', 261.05);
INSERT INTO countries(country_code, country_name) VALUES ('KE', 'Kenya', 80.92);
INSERT INTO countries(country_code, country_name) VALUES ('KI', 'Kiribati', 1.02);
INSERT INTO countries(country_code, country_name) VALUES ('KP', 'Korea, Democratic People''s Republic of', null);
INSERT INTO countries(country_code, country_name) VALUES ('KR', 'Korea, Republic of', 872.21);
INSERT INTO countries(country_code, country_name) VALUES ('XK', 'Kosovo', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('KW', 'Kuwait', 0.24);
INSERT INTO countries(country_code, country_name) VALUES ('KG', 'Kyrgyzstan', 54.16);
INSERT INTO countries(country_code, country_name) VALUES ('LA', 'Lao People''s Democratic Republic', 6498.40);
INSERT INTO countries(country_code, country_name) VALUES ('LV', 'Latvia', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('LB', 'Lebanon', 1178.80);
INSERT INTO countries(country_code, country_name) VALUES ('LS', 'Lesotho', 11.14);
INSERT INTO countries(country_code, country_name) VALUES ('LR', 'Liberia', 93.34);
INSERT INTO countries(country_code, country_name) VALUES ('LY', 'Libyan Arab Jamahiriya', 1.08);
INSERT INTO countries(country_code, country_name) VALUES ('LI', 'Liechtenstein', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('LT', 'Lithuania', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('LU', 'Luxembourg', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('MO', 'Macau', 6.29);
INSERT INTO countries(country_code, country_name) VALUES ('MK', 'Macedonia', 41.38);
INSERT INTO countries(country_code, country_name) VALUES ('MG', 'Madagascar', 2474.10);
INSERT INTO countries(country_code, country_name) VALUES ('MW', 'Malawi', 560.74);
INSERT INTO countries(country_code, country_name) VALUES ('MY', 'Malaysia', 3.31);
INSERT INTO countries(country_code, country_name) VALUES ('MV', 'Maldives', 12.19);
INSERT INTO countries(country_code, country_name) VALUES ('ML', 'Mali', 439.52);
INSERT INTO countries(country_code, country_name) VALUES ('MT', 'Malta', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('MH', 'Marshall Islands', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('MQ', 'Martinique', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('MR', 'Mauritania', 274.81);
INSERT INTO countries(country_code, country_name) VALUES ('MU', 'Mauritius', 26.89);
INSERT INTO countries(country_code, country_name) VALUES ('TY', 'Mayotte', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('MX', 'Mexico', 15.01);
INSERT INTO countries(country_code, country_name) VALUES ('FM', 'Micronesia, Federated States of', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('MD', 'Moldova, Republic of', 13.64);
INSERT INTO countries(country_code, country_name) VALUES ('MC', 'Monaco', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('MN', 'Mongolia', 1915.10);
INSERT INTO countries(country_code, country_name) VALUES ('ME', 'Montenegro', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('MS', 'Montserrat', 2.11);
INSERT INTO countries(country_code, country_name) VALUES ('MA', 'Morocco', 7.46);
INSERT INTO countries(country_code, country_name) VALUES ('MZ', 'Mozambique', 47.21);
INSERT INTO countries(country_code, country_name) VALUES ('MM', 'Myanmar', 1067.20);
INSERT INTO countries(country_code, country_name) VALUES ('NA', 'Namibia');
INSERT INTO countries(country_code, country_name) VALUES ('NR', 'Nauru', 1.02);
INSERT INTO countries(country_code, country_name) VALUES ('NP', 'Nepal');
INSERT INTO countries(country_code, country_name) VALUES ('NL', 'Netherlands', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('AN', 'Netherlands Antilles');
INSERT INTO countries(country_code, country_name) VALUES ('NC', 'New Caledonia');
INSERT INTO countries(country_code, country_name) VALUES ('NZ', 'New Zealand', 1.13);
INSERT INTO countries(country_code, country_name) VALUES ('NI', 'Nicaragua');
INSERT INTO countries(country_code, country_name) VALUES ('NE', 'Niger', 439.52);
INSERT INTO countries(country_code, country_name) VALUES ('NG', 'Nigeria');
INSERT INTO countries(country_code, country_name) VALUES ('NU', 'Niue', 1.13);
INSERT INTO countries(country_code, country_name) VALUES ('NF', 'Norfolk Island', 1.02);
INSERT INTO countries(country_code, country_name) VALUES ('MP', 'Northern Mariana Islands', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('NO', 'Norway');
INSERT INTO countries(country_code, country_name) VALUES ('OM', 'Oman');
INSERT INTO countries(country_code, country_name) VALUES ('PK', 'Pakistan');
INSERT INTO countries(country_code, country_name) VALUES ('PW', 'Palau', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('PS', 'Palestine');
INSERT INTO countries(country_code, country_name) VALUES ('PA', 'Panama', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('PG', 'Papua New Guinea');
INSERT INTO countries(country_code, country_name) VALUES ('PY', 'Paraguay');
INSERT INTO countries(country_code, country_name) VALUES ('PE', 'Peru');
INSERT INTO countries(country_code, country_name) VALUES ('PH', 'Philippines');
INSERT INTO countries(country_code, country_name) VALUES ('PN', 'Pitcairn', 1.13);
INSERT INTO countries(country_code, country_name) VALUES ('PL', 'Poland');
INSERT INTO countries(country_code, country_name) VALUES ('PT', 'Portugal', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('PR', 'Puerto Rico', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('QA', 'Qatar');
INSERT INTO countries(country_code, country_name) VALUES ('RE', 'Reunion');
INSERT INTO countries(country_code, country_name) VALUES ('RO', 'Romania');
INSERT INTO countries(country_code, country_name) VALUES ('RU', 'Russian Federation');
INSERT INTO countries(country_code, country_name) VALUES ('RW', 'Rwanda');
INSERT INTO countries(country_code, country_name) VALUES ('KN', 'Saint Kitts and Nevis', 2.11);
INSERT INTO countries(country_code, country_name) VALUES ('LC', 'Saint Lucia', 2.11);
INSERT INTO countries(country_code, country_name) VALUES ('VC', 'Saint Vincent and the Grenadines', 2.11);
INSERT INTO countries(country_code, country_name) VALUES ('WS', 'Samoa');
INSERT INTO countries(country_code, country_name) VALUES ('SM', 'San Marino', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO countries(country_code, country_name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO countries(country_code, country_name) VALUES ('SN', 'Senegal', 439.52);
INSERT INTO countries(country_code, country_name) VALUES ('RS', 'Serbia');
INSERT INTO countries(country_code, country_name) VALUES ('SC', 'Seychelles');
INSERT INTO countries(country_code, country_name) VALUES ('SL', 'Sierra Leone');
INSERT INTO countries(country_code, country_name) VALUES ('SG', 'Singapore');
INSERT INTO countries(country_code, country_name) VALUES ('SK', 'Slovakia', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('SI', 'Slovenia', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('SB', 'Solomon Islands');
INSERT INTO countries(country_code, country_name) VALUES ('SO', 'Somalia');
INSERT INTO countries(country_code, country_name) VALUES ('ZA', 'South Africa');
INSERT INTO countries(country_code, country_name) VALUES ('GS', 'South Georgia South Sandwich Islands');
INSERT INTO countries(country_code, country_name) VALUES ('ES', 'Spain', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('LK', 'Sri Lanka');
INSERT INTO countries(country_code, country_name) VALUES ('SH', 'St. Helena');
INSERT INTO countries(country_code, country_name) VALUES ('PM', 'St. Pierre and Miquelon');
INSERT INTO countries(country_code, country_name) VALUES ('SD', 'Sudan');
INSERT INTO countries(country_code, country_name) VALUES ('SR', 'Suriname');
INSERT INTO countries(country_code, country_name) VALUES ('SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO countries(country_code, country_name) VALUES ('SZ', 'Swaziland');
INSERT INTO countries(country_code, country_name) VALUES ('SE', 'Sweden');
INSERT INTO countries(country_code, country_name) VALUES ('CH', 'Switzerland');
INSERT INTO countries(country_code, country_name) VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO countries(country_code, country_name) VALUES ('TW', 'Taiwan');
INSERT INTO countries(country_code, country_name) VALUES ('TJ', 'Tajikistan');
INSERT INTO countries(country_code, country_name) VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO countries(country_code, country_name) VALUES ('TH', 'Thailand');
INSERT INTO countries(country_code, country_name) VALUES ('TG', 'Togo', 439.52);
INSERT INTO countries(country_code, country_name) VALUES ('TK', 'Tokelau', 1.13);
INSERT INTO countries(country_code, country_name) VALUES ('TO', 'Tonga');
INSERT INTO countries(country_code, country_name) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO countries(country_code, country_name) VALUES ('TN', 'Tunisia');
INSERT INTO countries(country_code, country_name) VALUES ('TR', 'Turkey');
INSERT INTO countries(country_code, country_name) VALUES ('TM', 'Turkmenistan');
INSERT INTO countries(country_code, country_name) VALUES ('TC', 'Turks and Caicos Islands', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('TV', 'Tuvalu', 1.02);
INSERT INTO countries(country_code, country_name) VALUES ('UG', 'Uganda');
INSERT INTO countries(country_code, country_name) VALUES ('UA', 'Ukraine');
INSERT INTO countries(country_code, country_name) VALUES ('AE', 'United Arab Emirates');
INSERT INTO countries(country_code, country_name) VALUES ('GB', 'United Kingdom');
INSERT INTO countries(country_code, country_name) VALUES ('US', 'United States', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('UM', 'United States minor outlying islands', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('UY', 'Uruguay');
INSERT INTO countries(country_code, country_name) VALUES ('UZ', 'Uzbekistan');
INSERT INTO countries(country_code, country_name) VALUES ('VU', 'Vanuatu');
INSERT INTO countries(country_code, country_name) VALUES ('VA', 'Vatican City State', 0.68);
INSERT INTO countries(country_code, country_name) VALUES ('VE', 'Venezuela');
INSERT INTO countries(country_code, country_name) VALUES ('VN', 'Vietnam');
INSERT INTO countries(country_code, country_name) VALUES ('VG', 'Virgin Islands (British)', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('VI', 'Virgin Islands (U.S.)', 0.78);
INSERT INTO countries(country_code, country_name) VALUES ('WF', 'Wallis and Futuna Islands');
INSERT INTO countries(country_code, country_name) VALUES ('EH', 'Western Sahara');
INSERT INTO countries(country_code, country_name) VALUES ('YE', 'Yemen');
INSERT INTO countries(country_code, country_name) VALUES ('ZR', 'Zaire');
INSERT INTO countries(country_code, country_name) VALUES ('ZM', 'Zambia');
INSERT INTO countries(country_code, country_name) VALUES ('ZW', 'Zimbabwe', 0.78);